### PR TITLE
Issue 8, Issue 10 and Issue 11

### PR DESCRIPTION
**Pull request by hubenjamin**
Initial draft of (1) Issue 8 how to become a reviewer; (2) Issue 10 CLA verification; (3) Issue 11 how to sign CLA

### CODE REVIEW

**Comment by tobie** [comment]
Please adhere to the contribution guidelines and make atomic pull requests (using topic branches) as there's no way I can pull this in without doing some painful integration work on my machine. If you don't know how that works, I'm sure it is described in some of the TTWF resources and needs to be documented for others not to waste time with this. Opened a new issue here: #29

**Comment by tobie** [comment]
I did take a look at the work you did so far. The work that needs to be done here is essentially to compile existing resources, not come up with new content. There are far more complete guides to the review process in the WG wikis, for example, than what you wrote from scratch here.

Also, style wise, let's keep things simple. This should be fun, agreed, but is essentially technical documentation for people to get stuff done.

If a page has one line useful content it's probably either that I screwed up and shouldn't have assigned it a whole page  or that you're documenting the wrong thing.

**Comment by hubenjamin** [comment]
Thanks for the comments. If the comments could be more specific, it would be much more helpful. For example:

(1) topic branches: do you want me to create a separate branch for each issue? That might be too many branches. I can do either a standalone directory under current branch gh-pages, or a new branch for all of my work. A standalone directory under current branch is even better.

(2) painful integration work: since I have no visibility of the structure of your machine, I don't know exactly what the pain is. But my work are all new files, and it won't impact any existing code / doc or anything else on your machine. As I suggested in (1), I can create a standalone directory in gh-pages for all of my work to make it cleaner. BTW, do you have naming convention for directory and file?

(3) With regard to "the review process in the WG wikis", the Issue 13 is about Review Process. But my submission is Issue 8 "How to become a Reviewer". Maybe I misunderstood your intention here. If you meant the Review Process, similar to Issue 13, then I can doc the whole review procee in Issue 8. But it may overlap with Issue 13. Of course, we can have both if that's what you expect.

(4) With regard to "one line useful content", you already know "There is no up and running solution for this atm" in Issue 10. I will try to find more information with regard to "Verify CLA". For Issue 11 "Sign CLA", I think that's pretty much what we are currently doing now - at least that's the process how I signed CLA. But do let me know if I missed anything.

Thanks and looking forward to getting our job done better with expected quality.

**Comment by tobie** [comment]
> Thanks for the comments. If the comments could be more specific, it would be much more helpful. For example:

Yeah, sorry. I'm doing my best given the short time I have available for this.

> (1) topic branches: do you want me to create a separate branch for each issue?

Absolutely. This is the most common way of working with Git.

> That might be too many branches.

Nope, you should be just fine.

> I can do either a standalone directory under current branch gh-pages, or a new branch for all of my work. A standalone directory under current branch is even better.

Neither of those are good ideas or common practice in Git.

> (2) painful integration work: since I have no visibility of the structure of your machine, I don't know exactly what the pain is.

That has nothing to do with my machine/setup. Integrating atomic commits on GitHub is a breeze: you can be done in a couple of clicks using the web client. Otherwise I'll have to pull the whole tree into my local repository and cherry pick the commits which are ready to be committed. That's make work. I won't have the time for this.

> But my work are all new files, and it won't impact any existing code / doc or anything else on your machine.

That's irrelevant, I want to be able to merge full branches the way GitHub is setup to work, directly from the web client.

> As I suggested in (1), I can create a standalone directory in gh-pages for all of my work to make it cleaner.

That's an SVN convention. Doesn't make sense in a distributed environment.

> BTW, do you have naming convention for directory and file?

As mentioned above, directories won't be necessary. File names will be used directly for their url so please pick meaningful lowercase names.

> (3) With regard to "the review process in the WG wikis", the Issue 13 is about Review Process. But my submission is Issue 8 "How to become a Reviewer". Maybe I misunderstood your intention here. If you meant the Review Process, similar to Issue 13, then I can doc the whole review procee in Issue 8. But it may overlap with Issue 13. Of course, we can have both if that's what you expect.

My bad. We don't have a formalized process for becoming a reviewer yet. Deferring this to post-launch.

> (4) With regard to "one line useful content", you already know "There is no up and running solution for this atm" in Issue 10. I will try to find more information with regard to "Verify CLA". For Issue 11 "Sign CLA", I think that's pretty much what we are currently doing now - at least that's the process how I signed CLA. But do let me know if I missed anything.

Yup. Think you're mixing up the documentation CLA with the test contribution CLA. The former is using CLAHub, the latter isn't. We'd like to use something like CLAHub for test contribs. CLAHub might not fit the bill for this though and we might have to build a custom solution. In the meantime, we want to document the existing practice which is a rather convoluted solution. Afaik, it is documented on the TTWF website.

> Thanks and looking forward to getting our job done better with expected quality.

Yes. Again, please keep in mind our job is essentially one of editor and compiler of existing work gere than one of author.

I suggest you get acquainted with the existing documentation, find out which one is useful and uptodate, and pull it in.

**Comment by hubenjamin** [comment]
Thank you for the clarification, now it's much clearer to me.

Yes, it's a learning process, and I am happy to always learn something new while getting the work done.

Thank you again

**Comment by tobie** [comment]
Yeah. Sorry. I assumed working knowledge of Git and GitHub. Should have asked.

**Pull request closed without merging**
