### PR TITLE
answered the css repo + shepherd Q's and added a couple more that have come up recently

### PR DESCRIPTION
**Pull request by rhauck**
@plinss - can you review my responses to the CSS repo and the Shepherd questions and make sure I'm answering them satisfactorily?

@tobie - the "who else..." question could be merged with "which browser vendors..." more generally as "who runs these tests?" - we've had this asked at multiple TestTWF events. You ok with that?

The one I added about updating tests when specs change came up from my recent CSS 2.1 errata exercise. I honestly don't know the answer and will poll the CSS WG on how it's been done in the past (@plinss - if you have any input here as well, greatly appreciated). I'd also like to poll other WGs and compile the responses here. I'll take that to the mail lists.

Last, the one I added about running automated reftests - we've been asked that one at TestTWF events as well. I'm hoping for you or @automatedtester to maybe fill in the blank here with WebDriver info (I'm kinda curious where we're at with that anyway :) )

### CODE REVIEW

**Comment by rhauck** [comment]
I'll leave this open until I hear back from you guys, but I can eventually handle the merging.

**Comment by plinss** [comment]
The CSS repo and Shepherd responses are fine. The only caveat is that while the Shepherd/GitHub integration plans are unchanged, the plan to merge our repo with the main repo is currently on hold. The apparent direction for the main repo and its infrastructure currently don't appear to care about addressing the CSSWG's testing needs and my inquiries in that direction have gone unanswered. Unless and until this is resolved I'm not going to spend any energy working on integrating the repositories and we'll keep relying on our own tools.

**Comment by tobie** [comment]
> the "who else..." question could be merged with "which browser vendors..." more generally as "who runs these tests?" - we've had this asked at multiple TestTWF events. You ok with that?

Yes.

**Comment by tobie** [comment]
> The only caveat is that while the Shepherd/GitHub integration plans are unchanged, the plan to merge our repo with the main repo is currently on hold.

Well, that's a shame.

> The apparent direction for the main repo and its infrastructure currently don't appear to care about addressing the CSSWG's testing needs and my inquiries in that direction have gone unanswered.

I'll be addressing those on the mailing list asap - I've been away, sorry.

> Unless and until this is resolved I'm not going to spend any energy working on integrating the repositories and we'll keep relying on our own tools.

The focus on W3C process rather than interoperability is rather surprising. Does this reflect the consensus of the WG or is this your personal opinion?

That said, I don't see why we can't have a solution that satisfies both use cases. Shall we try working together instead of having knee-jerk reactions like that?

**Comment by plinss** [comment]
> > The only caveat is that while the Shepherd/GitHub integration plans are unchanged, the plan to merge our repo with the main repo is currently on hold.
> 
> Well, that's a shame.

Agreed.

> The focus on W3C process rather than interoperability is rather surprising. 

Frankly the publicly stated complete disregard for the W3C process in the W3C testing infrastructure group is completely shocking to me. 

The CSSWG has always been clear on the focus of our testing efforts, the first step is to get the spec to REC, then the testing effort shifts focus to broader interop testing.

> Does this reflect the consensus of the WG or is this your personal opinion?

As I previously explained, the CSSWG follows the W3C process and cares about getting our specs to REC. My personal opinion on that front is irrelevant.

> That said, I don't see why we can't have a solution that satisfies both use cases. 

Me neither, but all my efforts in that direction so far have been in vain.

> Shall we try working together instead of having knee-jerk reactions like that?

Working together would be a nice change. I've been trying for months, but every time I raise a concern or make a suggestion I'm either ignored or told that the CSSWG's needs don't matter. When other testing needs are raised, existing solutions that the CSSWG have already developed and refined over the course of years are ignored and re-invented. This isn't a knee jerk reaction but the only rational path forward for the CSSWG at this point and is the result of months of frustration on my part.

**Comment by tobie** [comment]
> Frankly the publicly stated complete disregard for the W3C process in the W3C testing infrastructure group is completely shocking to me.

The main goal of the effort I'm leading at W3C is to improve user agent interoperability and implementation quality through testing. It is not to help WG to move specs along the REC track. As previously stated however, I don't see how both couldn't go hand in hand.

> > That said, I don't see why we can't have a solution that satisfies both use cases.
> 
> Me neither, but all my efforts in that direction so far have been in vain.

Pointers to those efforts would be helpful.

> > Shall we try working together instead of having knee-jerk reactions like that?
> 
> Working together would be a nice change. I've been trying for months, but every time I raise a concern or make a suggestion I'm either ignored or told that the CSSWG's needs don't matter.

Pointers to when this happened would be useful.

> When other testing needs are raised, existing solutions that the CSSWG have already developed and refined over the course of years are ignored and re-invented.

I guess this is the sign that the solutions developed by the CSSWG do not meet the requirements of other groups nor those of the effort I'm leading.

As I've explained before, there's a number of external factors that changed since the CSSWG started developing its toolset (notably, WebDriver, Git and GitHub). I think that explains some of the discrepancies in the requirements.

> This isn't a knee jerk reaction but the only rational path forward for the CSSWG at this point and is the result of months of frustration on my part.

I do not understand what has happened over the course of the last weeks that warrant this change in plans. I also haven't seen this discussed on the CSSWG mailing list nor in conf call minutes, so I'm again unsure whether that decision reflects the informed opinion of the CSSWG or your personal choice.

**Comment by AutomatedTester** [comment]
@rhauck

```
As for WebDriver and reftests the way we are using them together is WebDriver bootstraps the reftests. Currently we only do this for Firefox OS.





I hope that helps

—
```

**Comment by jgraham** [comment]
It seems to me that a lot of the conversation on this bug would be better on the mailing list. Can we avoid fragmenting the discussion by only using github issues to make specific comments on PRs rather than as a general forum for questions and discussion?

**Comment by rhauck** [comment]
I agree with you except the conversation here is/was actually about this PR where I explicitly asked those who responded for review & input. Granted, the input provided on part of the PR took a tangential turn and this PR morphed into a detour route for an existing (but unresolved) thread. It eventually found its way back there though.

This particular doc may invoke more discussion as other questions here are filled in. Virtually all of the content on this page is derived from questions raised on the list - some with definitive answers, others still without. So going forward, you're point is well taken. As we touch other parts of this doc, we should try resurrect the corresponding thread or start new threads if needed. However, I do sincerely hope that those who take the time to respond to questions on the list will take the time to contribute their wisdom here. It'd be great if this FAQ can be a clean, distilled summary of the many days/weeks/months of threads on the list that are frankly sometimes very painful to trudge through when looking for answers.

**Comment by rhauck** [comment]
And since I got all the feedback I wanted here, closing. :)

**Comment by tobie** [comment]
@jgraham agreed.

@rhauck, @jgraham brought back this conversation to the main thread here: http://lists.w3.org/Archives/Public/public-test-infra/2013JulSep/0163.html

**Pull request merged**
