### PR TITLE
Issue 29: Github 101 Document how to work with Github

### PR DESCRIPTION
**Pull request by hubenjamin**
Based on http://testthewebforward.org/resources/github_test_submission.html

### CODE REVIEW

**Comment by hubenjamin** [comment]
Most recent commit hubenjamin@6381666ca8c2dd7afed7fa6eda7b36e9a8b65bad.

**Comment by hubenjamin** [comment]
It's been pushed 9 minutes ago.

**Comment by tobie** [comment]
I don't know if that has to do with the repo name change or something weird you're doing, but on your github repo, the branch you're working from for this pull request hasn't been updated.

Here, on the other hand, all the comments seem totally detached from the commit. I've never seen that before, and frankly I have no clue how to proceed reviewing your changes.

Once you make a pull request you must continue working on the same branch for follow-ups, if not we completely loose context, unless of course there are some massive screw-ups like in you initial commits and someone asks you to resend a new pull request.

**Comment by hubenjamin** [comment]
Thank you very much James for the guidance. You are correct, and the only extra I did was that I fetched from upstream and back-merged to my "issue29" branch (PR branch) because I see some new updates in upstream. Looks like once it is branched out, it needs to be kept stable. Thanks again James.

**Comment by hubenjamin** [comment]
James, there is a new commit hubenjamin@5ad67610c9a6d145201bf3a902a512a9dc31b0ed based on your most recent comments. Please review at your convenience. Thank you very much.

**Comment by jgraham** [comment]
I think this is good enough to merge; we can work on other issues later.

**Pull request merged**
