### PR TITLE
Updated page for Seoul event.

### PR DESCRIPTION
**Pull request by cynthia**
Ignore the previous PR, one last minute change came in.

### CODE REVIEW

**Comment by cynthia** [comment]
@rhauck Sorry for the noise, scratch the previous one...

**Comment by rhauck** [comment]
no problem - I can look at this now. #235 is the one, right?

**Comment by cynthia** [comment]
Yes, #235 is the correct one.

**Comment by cynthia** [comment]
Hold on to this merge! I just noticed that our a11y contributors clobbered the other translations and overwrote it with Korean. (...)

Lemme see if I can come up with a quick hack to work around this...

**Comment by cynthia** [comment]
There we go. It's not pretty, but we only have a week so I think we'll need to settle for "well, it works".

**Comment by rhauck** [comment]
LGTM now.  Stellar hack documentation :+1:

**Pull request merged**
