### PR TITLE
Discussion

### PR DESCRIPTION
**Pull request by hubenjamin**
According to your instruction on Issue 30

### CODE REVIEW

**Comment by tobie** [comment]
Same problem.

**Comment by hubenjamin** [comment]
See my additional comments on Issue 7 about 10 minutes ago. I just did the following:

git checkout gh-pages
git rm "4 old files"
git commit
git push origin gh-pages

Those old 4 files are gone in my gh-pages branch.

Now my issue7 branch and discussion branch has only the new "help-resources.md" (except those forked from your site), but gh-pages and master branch only has the files forked from your site.

Is this still the same problem now?

**Comment by tobie** [comment]
Yes. See commit list above.

**Comment by hubenjamin** [comment]
Strange. Now, in my https://github.com/hubenjamin/ttwf-docs, everything is clean at each branch.

Let me try to google some help. Sorry and thanks

**Comment by hubenjamin** [comment]
What if I issue another pull request from my gh-pages to your gh-pages, which essentially add those junk files first (last week), then remove them (today's), and effectively files impacted is 0. This way will clean up all the old pull requests, while keep the repository intact. What do you think? Worth trying? Thanks

**Comment by tobie** [comment]
I'd like to keep a clean history in the gh-branch if possible.

**Pull request closed without merging**
